### ISSUE TITLE
User support form 

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#104]
We may want to bump this to a first-release requirement.
A get help form will require users to categorize their issues and provide more information than the current email scheme does.  It could just deliver an email to a list address, or open an issue somewhere.
We can scope requirements with the DKRZ User Support women.

**Comment by tomvothecoder** [comment]
I have added this on Jira as a task. I plan on converting over to GitHub completely for managing issues and tasks after the v1.0 release.

https://acme-climate.atlassian.net/browse/MG-514?atlOrigin=eyJpIjoiMDNlY2I5Y2FjOGQzNDYzMmI0NTI1NGFkNjhmMDA2MzUiLCJwIjoiaiJ9
