### ISSUE TITLE
Fix default facets in the search query (latest and replica)

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#165]
**Describe the bug**
When I click on Show Replicas, the data nodes hosting original data no longer appear.  CoG shows original + replica data

**Desktop (please complete the following information):**
MacOS
Firefox

**To Reproduce**

Select "CMIP6" , press the Blue button
click the "Include Replicas" checkbox
click on data node dropdown and expand to show the nodes list

**Expected behavior**

All data_nodes that serve data matching the query and corresponding results should be present original and replica.

Probably on the backend, the search should drop the "replica=true" as that only provides replicas "replica=false" is ok for a default.  Should including replicas be a default since LLNL is more reliable than many original sites for the same data?

**Assignee Checklist**

Back-end
- [x] Update Cart/Search model to remove `default_facets` field 
- [x] Add `result_type` char field with options

Front-end
- App.tsx
  - [x] Remove `defaultFacets` state and `DefaultFacets` type
  - [x] Update handleClearFilters()
- Facets.tsx
  - [x] Remove `defaultFacets` prop
  - [x] Update `onSetFacets`
  - FacetsForm.tsx
    - [x] Remove references to `defaultFacets`
    - [x] Add drop down form for Result Type
- Search.tsx
  - [x] Remove `defaultFacets` prop
  - [x] Update `stringifyFilters`
  - [x] Use object destructuring for `activeSearchQuery` properties
  - types.ts
    - [x] Remove defaultFacets attribute from UserSearchQuery
    - [x] Add defaultFacets attribute to UserSearchQuery
      - [x] Fix references
- api.ts
  - [x] Update `generateSearchURLQuery`
  - [x] Add function that converts `resultType` to a URL param for replicas 
- Carts/types.ts
  - [x] Remove `defaultFacets` from `UserSearchQuery` type

**Comment by tomvothecoder** [comment]
User support team suggestion:
'instead of "Include replicas" --> "Include all nodes hosting exact copies (replicas)"'
