### ISSUE TITLE
Add filename variable filtering

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#166]
In reviewing the search features, just want to get down several in CoG so we will be on parity

Filename variable filter, hidden in CoG under `More Search Options`. 

This basically just adds `query=` param used for free-text search but for a specific dataset's files. (e.g. `query=solar`). 
The results apply for `List Files`, wget, and Globus
- it does NOT apply to the 'base' query related to datasets

---
**Assignee Checklist**

- Back-end
  - Search/models.py
    - [x] Add `filename_var` to Search model
- Front-end
  - `App.tsx`
    - [x] Add attribute `filenameVars` to `activeSearchQuery` state and `ActiveSearchQuery` and `UserSearchQuery` types
    - [x] Update references to types for new attribute
    - [x]  Add `handleOnSetFilenameVars` 
    - [x] Update `handleRemoveFilter` to handle `filename_vars`
  - `Facets.tsx`
    - [x] Add prop `onSetFilenameVars`
    - [x] Update `handleUpdateFacetsForm` to handle `filename_vars` form item
    - [x] Move `handleUpdateFacetsForm` to FacetsForm as `handleOnChangeFacetsForm`
    - FacetsForm.tsx
      - [x] Add text form item for `filename_vars`
      - [x] Add tooltip
      - [x] Add handleOnFinishFilenameVarForm 
  - `Search.tsx`
    - [x] Add tags for Filename variables on a separate line (distinguish with dataset filter tags)
    - `Table.tsx`
      - [ ] ~~Add `More Info` column header for expandable~~ **Ant Design Table API does not have this feature**
      - [x] Update `More Info` link to `ES-DOC` 
      - [x] Use `filenameVars` for wget API
  - `FilesTable.tsx`
     - [x] Add props `filenameVars` and `numResults`
     - [x] Add `useEffect` to automatically invoke `runFetchDatasetFiles` on prop updates
     - [x] Add drop down for metadata 
     - [x] Add pagination
  - `Cart.tsx`
    - `SearchesCard.tsx`
       - [x] Render `filename_vars` as string

**Comment by tomvothecoder** [comment]
- [ ] Show all versions (drop latest=true from search)

Moved this to #165
