### ISSUE TITLE
Add technical notes and supplemental data links

### ISSUE THREAD

**Issue by tomvothecoder** [aims-group/metagrid#194]
**Describe the solution you'd like**

In the search results, links for "Tech Notes" and "Supplementary Data" appear mainly for obs4MIPs

The reference code is in the following file in CoG:
https://github.com/EarthSystemCoG/COG/blob/master/cog/templates/cog/search/_record_display.html

Some tech notes have been published as "summary" in the xlink field. Others contain the label.

Example result json https://esgf-node.llnl.gov/esg-search/search?offset=0&limit=100&type=Dataset&replica=false&latest=true&variable=tro3&data_node=aims3.llnl.gov&project=obs4MIPs&format=application%2fsolr%2bjson

Example with PID + Tech Note as "summary":    
```     
"xlink":["http://esgf1.dkrz.de/thredds/fileServer/obs4MIPs/obs4MIPs/observations/FUB-DWD/Obs-SSMI-MERIS/obs/mon/atmos/prw/Obs4MIPsTechnicalNote_GlobVapour_FUB-DWD_mon_prw_SSMI-MERIS_L3_v1-00_200301-200812.pdf|Technical Note|summary",
          "http://hdl.handle.net/10876/ESGF/4ee9d37b-6454-44bf-b3ef-e738b2ecedb4|PID|pid"],
```
Also see: https://github.com/EarthSystemCoG/COG/blob/master/cog/services/SolrSerializer.py
Some massage of the url fields separated by `|` done here

**Comment by sashakames** [comment]
In the search results, links for "Tech Notes" and "Supplementary Data" appear mainly for obs4MIPs

The reference code is in the following file in CoG:
https://github.com/EarthSystemCoG/COG/blob/master/cog/templates/cog/search/_record_display.html

Some tech notes have been published as "summary" in the xlink field. Others contain the label.

Example result json https://esgf-node.llnl.gov/esg-search/search?offset=0&limit=100&type=Dataset&replica=false&latest=true&variable=tro3&data_node=aims3.llnl.gov&project=obs4MIPs&format=application%2fsolr%2bjson

**Comment by sashakames** [comment]
Example with PID + Tech Note as "summary":    
```     "xlink":["http://esgf1.dkrz.de/thredds/fileServer/obs4MIPs/obs4MIPs/observations/FUB-DWD/Obs-SSMI-MERIS/obs/mon/atmos/prw/Obs4MIPsTechnicalNote_GlobVapour_FUB-DWD_mon_prw_SSMI-MERIS_L3_v1-00_200301-200812.pdf|Technical Note|summary",
          "http://hdl.handle.net/10876/ESGF/4ee9d37b-6454-44bf-b3ef-e738b2ecedb4|PID|pid"],
```
Also see: https://github.com/EarthSystemCoG/COG/blob/master/cog/services/SolrSerializer.py
Some massage of the url fields separated by `|` done here

**Comment by tomvothecoder** [comment]
> Example with PID + Tech Note as "summary":
> 
> ```
> "xlink":["http://esgf1.dkrz.de/thredds/fileServer/obs4MIPs/obs4MIPs/observations/FUB-DWD/Obs-SSMI-MERIS/obs/mon/atmos/prw/Obs4MIPsTechnicalNote_GlobVapour_FUB-DWD_mon_prw_SSMI-MERIS_L3_v1-00_200301-200812.pdf|Technical Note|summary",
>           "http://hdl.handle.net/10876/ESGF/4ee9d37b-6454-44bf-b3ef-e738b2ecedb4|PID|pid"],
> ```
> 
> Also see: https://github.com/EarthSystemCoG/COG/blob/master/cog/services/SolrSerializer.py
> Some massage of the url fields separated by `|` done here

Added to the issue description, thanks

**Comment by tomvothecoder** [comment]
A few noted issues:
- Supplementary Data link does not work
  - https://aims3.llnl.gov/obs4MIPs_misc/supplemental_info/TES-SUPPLEMENTARY.zip
- Some Technical Notes links don't work
  - https://eridanus.eoc.dlr.de/static/technotes/Obs4MIPs_Technical_Note_Aerosol_cci_SU_ATSR_v4.1.doc
