### ISSUE TITLE
Show All Versions / Latest version

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#257]
#### Is your feature request related to a problem? Please describe

To put us on feature parity with CoG, searches should have an option to include older versions of datasets.

#### Describe the solution you'd like

The default search should only show the most recent version (inlcudes &latest=true)
The toggle should drop the parameter to include all versions of dataset.  

There is no use case to include "&latest=false"  so no need to consider a third option

**Comment by sashakames** [comment]
Example:  project = E3SM
model_version = 1_0
experiment = historical
ensemble = ens5
13 datasets (latest only) -> default on CoG
21 (all version) appear on metagrid

**Comment by tomvothecoder** [comment]
### Implementation Checklist
Backend 
- [ ] Add field `version_type`
- [ ] Update SearchSerializer
- [ ] Add migration file

Frontend
- [ ] Add `version_type` attr to `RawUserSearchQuery` type
- [ ] Add `versionType` attr to `UserSearchQuery` type
- [ ] Add default value to `versionType` to `projectBaseQuery` 
- [ ] Add dropdown for "Version Type" with options for "Latest" and "All"
- [ ]  Update `handleOnFinishFilenameVarForm` to handle "Version Type" form
