### ISSUE TITLE
Add Globus support for downloading datasets and files

### ISSUE THREAD

**Issue by tomvothecoder** [aims-group/metagrid#264]
#### Is your feature request related to a problem? Please describe

Add Globus support as a viable, robust alternative method to wget for batch downloading datasets and files.

I've listed the two main approaches to the integration process.

### 1. Register our ESGF Keycloak server as an IdP on Globus
Pros:
- Single IdP for Keycloak and Globus
- Eliminates additional login pages
- Use Globus’s REST API to transfer tokens
- Simplifies implementation
- No additional layers of complexity since we only need to manage Keycloak
- Eliminates myproxy?
- Can work nicely with data authorization (e.g. restricted data)

Cons:
- Requires paid subscription since it is a “custom” IdP
- Rearchitect the auth flow and implement new code

### 2. Integrate using the existing flow (CoG)

Pros:
- No subscription required
- Already have the flow established, albeit clunky

Cons:
- Multiple accounts/IdPs for authentication
- Multiple login pages
- Complex implementation
- Increases the possible point of failures
- Have to use myproxy?
- In CoG, restricted data sometimes forces users to login again with OpenID
 
#### Describe the solution you'd like

I am leaning towards option 1 since it would be a substantial improvement for the end-user experience and simplifies developer integration.
 
We believe there aren’t many users using Globus at the moment. I think contributing factors include users not wanting to manage multiple accounts and its clunky integration with CoG. If we streamline the process between the UI and Globus, we might be able to attract more users to use Globus as a reliable data transfer service. Keycloak will also be established as the single source of truth for authentication across ESGF.
 
If we implement option 1 and figure out a way to gather metrics on Globus’s usage over time, it could be a worthwhile investment.

**Comment by sashakames** [comment]
Deployment on aims2 makes this complete :tada:
