### ISSUE TITLE
Fix wording of search fields for better clarity

### ISSUE THREAD

**Issue by downiec** [aims-group/metagrid#280]
### Describe the fix

Rename “Filename Variable” to “Filename Search” –> non-CMIP6 datasets don’t have variable name in the filename

**Comment by sashakames** [comment]
@downiec this needs more clarification as its not true for all projects

**Comment by downiec** [comment]
> @downiec this needs more clarification as its not true for all projects

@sashakames This issue was directly taken from the usability test feedback and proposed fixes. More info can be found on the confluence page (I won't link it here). We can update this issue as needed and I will close it if we decide to go a different route. The previous wording was also not true for all projects and that's why it was suggested we use more general terms? It is up for discussion how to address this and is a trivial fix when we decide what to do.
