### ISSUE TITLE
Make results table more compact

### ISSUE THREAD

**Issue by tomvothecoder** [aims-group/metagrid#289]
#### Is your feature request related to a problem? Please describe
Make the results table more compact so that it fits better on smaller screens and optimized to show highest priority items.

Suggestions
- Remove Node column
- Update ordering of columns by priority
- Remove unnecessary columns (e.g. checksum)
- Rename “# of files” to “files”
- Remove Total Size and abbreviate "Node"

**Comment by sashakames** [comment]
New observation.  Search in the Obs4MIPs space and look at the "Additional" column.  I think Tom took a "general" approach by using the CoG code as a reference. I had forgotten about this case when we went over the columns, but hopefully not a major impact, but something to be aware of.

**Comment by downiec** [comment]
I just tried now and looks like the 'Additional; column is empty with obs4mips.
I can try to add some logic so that if the content is empty, then the column won't show up? Or is there something I should do so that content shows up there properly?
