### ISSUE TITLE
Make facets sidebar more compact

### ISSUE THREAD

**Issue by tomvothecoder** [aims-group/metagrid#290]
#### Is your feature request related to a problem? Please describe
Make the facets sidebar more compact so that it fits better on smaller screens.

Suggestions
- Reduce spacing
- Reduce font size?
- Reduce component sizes

**Comment by sashakames** [comment]
Suggestion.  Start the facets right under project select.  The misc search widgets (not facets) are of secondary importance and could be hidden/shown or relocated
