### ISSUE TITLE
Correct "Copy Search" 

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#340]
### Describe the bug

Copy search URLs are incorrectly formatted

#### To Reproduce

Perform a search.  Click the Copy Search button

example:
```
https:esgf-dev1.llnl.gov
  /metagrid/search?project=CMIP6&data=%7B%22activeFacets%22%3A%7B%22source_id%22%3A%5B%22EC-Earth3-CC%22%5D%2C%22experiment_id%22%3A%5B%22historical%22%5D%2C%22variant_label%22%3A%5B%22r8i1p1f1%22%5D%7D%7D
```
#### Expected behavior

URL needs proper scheme, and single line: eg:
https//:esgf-dev1.llnl.gov/metagrid/search?project=CMIP6&data=%7B%22activeFacets%22%3A%7B%22source_id%22%3A%5B%22EC-Earth3-CC%22%5D%2C%22experiment_id%22%3A%5B%22historical%22%5D%2C%22variant_label%22%3A%5B%22r8i1p1f1%22%5D%7D%7D

**Comment by downiec** [comment]
I wasn't able to reproduce this error when I tested it. Using the links shown there I get an error, but I couldn't create that link using. copy search feature. I noticed that variant_label r8i1p1f1 isn't an available option in the drop-downs in the app? What search terms could I use to try and duplicate this issue?

**Comment by sashakames** [comment]
project: CMIP6

activity_id : CMIP
source_id : E3SM-1-0
experiment_id : historical

problem on Firefox
