### ISSUE TITLE
Combining Anonymous and Authenticated cart and saved searches

### ISSUE THREAD

**Issue by downiec** [aims-group/metagrid#341]
#### Is your feature request related to a problem? Please describe

Currently, if the user saves items to their cart or the saved searches when logged out, the items are saved locally to the browser as an anonymous user. However if the user then decides to log in, their current searches and cart will be replaced with their cart and searches associated to their authenticated user.

#### Describe the solution you'd like

It may be preferable to have the saved items during an anonymous session copied over and saved to an authenticated session when a user logs in and vice versa, so that the authenticated and anonymous sessions are in-sync with each other and the user isn't confused by what happened to their respective cart when they logged in or out.

**Comment by sashakames** [comment]
For login:  Data carts / searches need to be merged, so we eliminate duplicate items.  Is there a approach we can use?  In the shell, the fastest way to do this is to (1) concat the lists (2) sort the lists (3) eliminate consecutive duplicates.  In Python use "set()"

**Comment by downiec** [comment]
The data cart / searches stuff is handled in typescript and there are methods that could allow us to avoid duplicates.
