### ISSUE TITLE
OpenDAP url extension correction

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#383]
Requesting a workaround for inconsistencies in opendap url publishing.

.nc should be the correct format.   Test if the case if so leave as is

Remove .dods.html, .dods .dods.nc .nc.dods  (will clarify which are present) and replace with .nc

**Comment by sashakames** [comment]
Definitely .dods

**Comment by tesfalem2** [comment]
Hi Sashakames, i have also same issues you mentioned. The file i have ends with xxxxxxxx.nc.dods. I use matlab to display or read but both not working do you have some tip with matlab?

**Comment by sashakames** [comment]
I also found .nc.html extensions
