### ISSUE TITLE
Master_id search

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#387]
If you put this in the CoG free-text box:  master_id:CMIP6.ScenarioMIP.CCCma.CanESM5.ssp126.r5i1p1f1.Omon.tauvo.gn
It produces a search result
Metagrid: breaks when searching CMIP6
  ```
There was an issue fetching search results. Please contact support or try again later.
```

**Comment by sashakames** [comment]
Action: @sashakames check CoG side of things to trace query.

**Comment by downiec** [comment]
I tested it just now and it appears to have been resolved.
