### ISSUE TITLE
Update browser URL as search is performed

### ISSUE THREAD

**Issue by downiec** [aims-group/metagrid#406]
Currently the url in the browser doesn't change as a user is performing a search and therefore to share the current search, users have to click on to the 'Copy Search' button.

#### Describe the solution you'd like

Feedback provided by Renata, suggests that we should update the link in the browser as a user adds/removes search criteria so that a user could bookmark the page and get the same search next time they visit the site.

We should dynamically update the URL parameters every time the search is updated/modified.

**Comment by sashakames** [comment]
This seems difficult to do with the "single page app" design.   If she asks again, we can explain that its a limitation of the design and would require significant changes.
