### ISSUE TITLE
download wget script for multiple datasets not working

### ISSUE THREAD

**Issue by RubenvanHooidonk** [aims-group/metagrid#441]
When selecting multiple datasets (184) and then clicking download next to wget at the bottom of the page results in the message:

The wget script is generating, please wait momentarily.

The message disappears, but no wget script is downloaded.

**Comment by sashakames** [comment]
Thank you @RubenvanHooidonk  for reporting this issue and apologies for the delay.  We are working on addressing this. I'll follow up if we need more information.
