### ISSUE TITLE
Cannot download wget script after adding datasets to the cart

### ISSUE THREAD

**Issue by harry9713** [aims-group/metagrid#446]
### Describe the bug

When trying to download the wget script after adding the dataset to the cart, it goes to another web page and says 

**404
Sorry, the page you visited does not exist.**

- OS: Ubuntu 18.04

- Browser and Version: Google Chrome Version 102.0.5005.115 (Official Build) (64-bit)

#### To Reproduce

Steps to reproduce the behaviour:
1. Go to  metagrid
2. select the data
3. add to cart
4. go to the cart , select the data and click download button under the download your cart.

Thanks.

**Comment by sashakames** [comment]
Thank you @harry9713  for reporting this issue.  We have confirmed the issue and working to address it.

**Comment by sashakames** [comment]
@downiec https://github.com/aims-group/metagrid/tree/446-cannot-download-wget-script We'll want to merge this branch and deploy to aims2 once we have the hotfix branch ready.  This might not be the comprehensive fix though for future deployments.

**Comment by harry9713** [comment]
> Thank you @harry9713 for reporting this issue. We have confirmed the issue and working to address it.

@sashakames Thanks for quickly addressing the issue. I was one of those people who were enjoying the new metagrid search interface, as it is fast, more straight forward and organised. I hope you will fix the issue as early as possible. If possible, consider revert back to a previous version which was working. Sorry if I am being stupid as I am not at all an expert in this. But this interface was part of my workflow these days. 

Thank you for your time.

**Comment by sashakames** [comment]
@harry9713  My guess is that your browser may somehow cached a bad version.  The site is running 
try this url: https://aims2.llnl.gov/metagrid/search
or a different browser, or private/incognito window?
 Can you upload a screeshot if the problem persists?

**Comment by sashakames** [comment]
We have the original issue corrected so closing...
