### ISSUE TITLE
zero length files returned on perlmutter with wget

### ISSUE THREAD

**Issue by mfwehner** [aims-group/metagrid#550]
### Describe the bug

Files downloaded are zero length
Wget Output looks like
HTTP request sent, awaiting response... 302 Found
Location: https://esgf-node.ornl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/CMIP/VUA/VUA-CMIP-BB4CMIP6-1-2/atmos/mon/SO2/gn/v20161213/SO2-em-biomassburning_input4MIPs_emissions_CMIP_VUA-CMIP-BB4CMIP6-1-2_gn_185001-201512.nc [following]
--2023-08-02 17:33:08--  https://esgf-node.ornl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/CMIP/VUA/VUA-CMIP-BB4CMIP6-1-2/atmos/mon/SO2/gn/v20161213/SO2-em-biomassburning_input4MIPs_emissions_CMIP_VUA-CMIP-BB4CMIP6-1-2_gn_185001-201512.nc
OpenSSL: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small

**Desktop (please complete the following information):**
<Mac OSX>
- OS:
<Google Chrome Version 87.0.4280.141 (Official Build) (x86_64) Version 115.0.5790.170 (Official Build) (x86_64)>

- Browser and Version:
<Google Chrome Version 87.0.4280.141 (Official Build) (x86_64) Version 115.0.5790.170 (Official Build) (x86_64)>
#### To Reproduce

<
<img width="1440" alt="Screen Shot 2023-08-02 at 5 43 14 PM" src="https://github.com/aims-group/metagrid/assets/10789148/c93274d6-a211-4946-9466-d63d1d0a4d02">
1. Go to input4mips, select CMIP, select SO2 or related files
2. add to cart
3. download wget
4. execute on perlmutter

I tried from ORNL with firefox and chrome same error.
wget at this location on perlmutter: /pscratch/sd/m/mwehner/wget-20230803003152.sh
>

**Comment by sashakames** [comment]
Apologies for not seeing the issue sooner.  Appears that the issue is decoupled from Metagrid and a site issue at ORNL
