### ISSUE TITLE
no coord ref

### ISSUE THREAD

**Issue by Metzli10** [aims-group/metagrid#564]
Hello, I downloaded your files and they have no geographical reference, which one should I assign them?

name file: thetao_Omon_FGOALS-f3-H_hist-1950_r1i1p1f1_gn_195001-195001.nc
link file: https://esgf-data1.llnl.gov/thredds/dodsC/css03_data/CMIP6/HighResMIP/CAS/FGOALS-f3-H/hist-1950/r1i1p1f1/Omon/thetao/gn/v20200917/thetao_Omon_FGOALS-f3-H_hist-1950_r1i1p1f1_gn_195001-195001.nc

**Comment by sashakames** [comment]
Hi, looks like this is an issue specific to OpenDAP, so I'm sorry to inform you it is out of scope for our repository issues.  You may want to look into help or discussion forums for netCDF data.
