### ISSUE TITLE
No wget script even after re-loading the website

### ISSUE THREAD

**Issue by harry9713** [aims-group/metagrid#567]
When trying to get the wget script after adding the files to the cart and selecting them, I am getting no response. When I click on the download button, it does not show anything.

Ubuntu 18.04
Google Chrome Version 116.0.5845.110 (Official Build) unknown (64-bit)

I am facing this randomly but more frequently in recent times. I am not able to find a pattern here. 

Thankyou

**Comment by wmadavis** [comment]
Same issue on both Chrome and Safari. My experience is that it was working two days ago but stopped working yesterday (clicking the button does not initiate any action).

**Comment by 870846704** [comment]
I have the same issure, which occurs frequently

**Comment by sashakames** [comment]
Hi all, I've confirmed that this issue is reproducible. 
FYI @downiec

**Comment by sashakames** [comment]
This was the case with non Globus transferable.  I used the first 10 items from RFMIP + the "umr-cnrm" data_node

**Comment by sashakames** [comment]
We have pushed a change to the server that corrects this issue.  I can verify resolution but note that your browser may cache the old broken version.  You may need to restart or even reboot.
