### ISSUE TITLE
This is urgent please. I can not log in to ESGF MetaGrid CMIP6 from past 3 days. Everything seems good but the website is down

### ISSUE THREAD

**Issue by salmabibi1** [aims-group/metagrid#569]
<img width="1257" alt="Screenshot 2023-10-31 at 3 21 19 AM" src="https://github.com/aims-group/metagrid/assets/149468208/53c211ca-5287-46f3-abf3-a3a754a2fadb">
I can not log in to ESGF MetaGrid CMIP6 from past 3 days. Everything seems good but the website is down.

I am using MacOSX. 

http://aims2.llnl.gov/search?project=CMIP6

### Describe the bug

**Desktop (please complete the following information):**

- OS:
<img width="1533" alt="Screenshot 2023-10-30 at 9 57 10 AM" src="https://github.com/aims-group/metagrid/assets/149468208/9e1711e2-0389-4e1c-9ea9-9ef3d01172da">

- Browser and Version:

#### To Reproduce

1.

#### Expected behavior
<img width="1533" alt="Screenshot 2023-10-30 at 9 57 10 AM" src="https://github.com/aims-group/metagrid/assets/149468208/88cbcf3f-b7b7-420d-8d66-534279334257">
<img width="1533" alt="Screenshot 2023-10-30 at 9 57 10 AM" src="https://github.com/aims-group/metagrid/assets/149468208/af8468fe-951b-4a59-83fc-7e79a8470411">

**Comment by sashakames** [comment]
Perhaps this was an intermittent issue, the site is up now without the errors shown.
