### ISSUE TITLE
Cannot load ESGF Search page: There was an issue fetching search results. 

### ISSUE THREAD

**Issue by franklintfcheng** [aims-group/metagrid#581]
Hello, this morning I found that I couldn't load the ESGF search page (https://aims2.llnl.gov/search/?project=CMIP6), it says "There was an issue fetching search results. Please contact support or try again later." Can anyone help? Thanks.

**Comment by rachel-mccrary** [comment]
I am also having this issue and cannot access other ESGF pages ... looks like the llnl ESGF pages are down?

**Comment by sashakames** [comment]
Hi, the search API that provides results to Metagrid is offline, sorry for the inconvenience.  We are working on restoring the site over the weekend.

**Comment by sashakames** [comment]
Please try another partner site in the meantime from this list:  https://esgf.llnl.gov/nodes.html

**Comment by franklintfcheng** [comment]
Hi @sashakames, many thanks for your prompt replies and your work over the weekend! I really appreciate it.

**Comment by sashakames** [comment]
Search is restored at aims2.llnl.gov
