### ISSUE TITLE
Unknown Error Has Occurred when trying to get a wget script

### ISSUE THREAD

**Issue by rachel-mccrary** [aims-group/metagrid#588]
I'm trying to download wget scripts and I keep getting "an unknown error has occurred" when the wget script is generating.  I didn't have any issues with this yesterday with the same model/node so I'm wondering what might be going on.  I'm using Mac OSC, Version 120.0.6099.216 (Official Build) (x86_64) and Safari Version 16.5.1 (18615.2.9.11.7).  Any ideas what might be going on and how to get around this issue?  Datasets don't seem to be available on globus.

**Comment by sashakames** [comment]
Hi, I'm able to generate a wget script for CMIP6 datasets using Safari.  Could you please give some example datasets that cause the error?

**Comment by rachel-mccrary** [comment]
Hmm I'm trying to finish downloading GISS-E2-1-G ssp370 sfcWind, tas, tasmax, and tasmin montly data.  However I've tried other models and nothing seems to be working.  I'll restart my computer and see if that fixes the issue.

**Comment by sashakames** [comment]
You might be able to create a wget script directly using a url: `wget -O script.sh 'https://esgf-node.llnl.gov/esg-search/wget?source_id=GISS-E2-1-G&experiment_id=ssp370&variable_id=tas,tasmin,tasmax,sfcWind'`

**Comment by rachel-mccrary** [comment]
OK - restarting my computer seems to have worked (thats good to know!) I had already tried rebooting my browser but that hadn't worked.  Also thanks for the tip about making the script directly using a URL!

**Comment by sashakames** [comment]
Additional suggestions before I close the issue: try another browser, eg., Chrome or Firefox.
